/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.JProgressBar;
import models.Patient;
import models.PatientDirectory;
import models.Person;
import models.PersonDirectory;
import ui.ComparePanel.MainComparePanel;
import ui.PatientPanel.MainPatientPanel;
import ui.PersonPanel.MainPersonPanel;

/**
 *
 * @author shreya
 */
public class DashboardPanel extends javax.swing.JPanel {

    /**
     * Creates new form DashboardPanel
     */
    private JPanel WorkAreaPanel;
    Person person;
    Patient patient;
    PersonDirectory personDirectory;
    PatientDirectory patientDirectory;
    public DashboardPanel(JPanel WorkAreaPanel, PersonDirectory personDirectory) {
        initComponents();
        this.WorkAreaPanel = WorkAreaPanel;
        this.personDirectory = personDirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainJPanel = new javax.swing.JPanel();
        lbltxtSummary = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel3 = new javax.swing.JLabel();
        jProgressBar2 = new javax.swing.JProgressBar();
        jLabel5 = new javax.swing.JLabel();
        jProgressBar3 = new javax.swing.JProgressBar();
        jLabel6 = new javax.swing.JLabel();
        jProgressBar4 = new javax.swing.JProgressBar();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblHeading = new javax.swing.JLabel();
        currentStudentJPanel1 = new javax.swing.JPanel();
        lblPatient = new javax.swing.JLabel();
        btnPatient = new javax.swing.JButton();
        lbltxtPatient = new javax.swing.JLabel();
        currentStudentJPanel = new javax.swing.JPanel();
        lblPerson = new javax.swing.JLabel();
        btnPerson = new javax.swing.JButton();
        lbltxtPerson1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 153, 255));

        mainJPanel.setBackground(new java.awt.Color(204, 204, 255));
        mainJPanel.setName(""); // NOI18N

        lbltxtSummary.setBackground(new java.awt.Color(255, 255, 255));
        lbltxtSummary.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lbltxtSummary.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltxtSummary.setText("2020-22 Year");

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));

        jProgressBar1.setBackground(new java.awt.Color(204, 204, 204));
        jProgressBar1.setForeground(new java.awt.Color(102, 102, 255));
        jProgressBar1.setValue(70);

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Average Blood Pressure");

        jProgressBar2.setBackground(new java.awt.Color(204, 204, 204));
        jProgressBar2.setForeground(new java.awt.Color(102, 102, 255));
        jProgressBar2.setValue(60);

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Average Heart Rate");

        jProgressBar3.setBackground(new java.awt.Color(204, 204, 204));
        jProgressBar3.setForeground(new java.awt.Color(102, 102, 255));
        jProgressBar3.setValue(95);
        jProgressBar3.setPreferredSize(new java.awt.Dimension(183, 10));

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Average Temperature");

        jProgressBar4.setBackground(new java.awt.Color(204, 204, 204));
        jProgressBar4.setForeground(new java.awt.Color(102, 102, 255));
        jProgressBar4.setValue(80);

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Average Respiratory Rate");

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setText("Average statistics of the City");

        javax.swing.GroupLayout mainJPanelLayout = new javax.swing.GroupLayout(mainJPanel);
        mainJPanel.setLayout(mainJPanelLayout);
        mainJPanelLayout.setHorizontalGroup(
            mainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainJPanelLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(104, 104, 104))
            .addGroup(mainJPanelLayout.createSequentialGroup()
                .addGroup(mainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jProgressBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(mainJPanelLayout.createSequentialGroup()
                            .addGap(138, 138, 138)
                            .addComponent(jLabel3))
                        .addGroup(mainJPanelLayout.createSequentialGroup()
                            .addGap(141, 141, 141)
                            .addComponent(jLabel5))
                        .addGroup(mainJPanelLayout.createSequentialGroup()
                            .addGap(105, 105, 105)
                            .addGroup(mainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jProgressBar4, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainJPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(mainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainJPanelLayout.createSequentialGroup()
                        .addGroup(mainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(lbltxtSummary, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(101, 101, 101))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainJPanelLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(118, 118, 118))))
        );
        mainJPanelLayout.setVerticalGroup(
            mainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainJPanelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel4)
                .addGap(17, 17, 17)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jProgressBar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jProgressBar4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(lbltxtSummary, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(147, 147, 147))
        );

        lblHeading.setBackground(new java.awt.Color(255, 255, 255));
        lblHeading.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        lblHeading.setForeground(new java.awt.Color(51, 51, 51));
        lblHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeading.setText("DASHBOARD");

        currentStudentJPanel1.setBackground(new java.awt.Color(153, 102, 255));
        currentStudentJPanel1.setForeground(new java.awt.Color(255, 255, 255));

        lblPatient.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        lblPatient.setForeground(new java.awt.Color(51, 51, 51));
        lblPatient.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPatient.setText("PATIENT");

        btnPatient.setBackground(new java.awt.Color(255, 255, 255));
        btnPatient.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnPatient.setText("Patient Dashboard");
        btnPatient.setPreferredSize(new java.awt.Dimension(160, 30));
        btnPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatientActionPerformed(evt);
            }
        });

        lbltxtPatient.setFont(new java.awt.Font("SansSerif", 3, 18)); // NOI18N
        lbltxtPatient.setText("<html>Log on to the Patient Dashboard <br> for creating, updating and deleting Patients");

        javax.swing.GroupLayout currentStudentJPanel1Layout = new javax.swing.GroupLayout(currentStudentJPanel1);
        currentStudentJPanel1.setLayout(currentStudentJPanel1Layout);
        currentStudentJPanel1Layout.setHorizontalGroup(
            currentStudentJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(currentStudentJPanel1Layout.createSequentialGroup()
                .addGroup(currentStudentJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(currentStudentJPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(btnPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbltxtPatient, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                        .addGap(42, 42, 42))
                    .addGroup(currentStudentJPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(lblPatient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        currentStudentJPanel1Layout.setVerticalGroup(
            currentStudentJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(currentStudentJPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblPatient)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(currentStudentJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, currentStudentJPanel1Layout.createSequentialGroup()
                        .addComponent(btnPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, currentStudentJPanel1Layout.createSequentialGroup()
                        .addComponent(lbltxtPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))))
        );

        currentStudentJPanel.setBackground(new java.awt.Color(153, 102, 255));
        currentStudentJPanel.setForeground(new java.awt.Color(255, 255, 255));

        lblPerson.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        lblPerson.setForeground(new java.awt.Color(51, 51, 51));
        lblPerson.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPerson.setText("PERSON ");

        btnPerson.setBackground(new java.awt.Color(255, 255, 255));
        btnPerson.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnPerson.setText("Person Dashboard");
        btnPerson.setPreferredSize(new java.awt.Dimension(160, 30));
        btnPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonActionPerformed(evt);
            }
        });

        lbltxtPerson1.setFont(new java.awt.Font("SansSerif", 3, 18)); // NOI18N
        lbltxtPerson1.setText("<html>Log on to the Person Dashboard <br> for creating, updating and deleting Persons");

        javax.swing.GroupLayout currentStudentJPanelLayout = new javax.swing.GroupLayout(currentStudentJPanel);
        currentStudentJPanel.setLayout(currentStudentJPanelLayout);
        currentStudentJPanelLayout.setHorizontalGroup(
            currentStudentJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(currentStudentJPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnPerson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbltxtPerson1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(currentStudentJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPerson, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(57, 57, 57))
        );
        currentStudentJPanelLayout.setVerticalGroup(
            currentStudentJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(currentStudentJPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblPerson)
                .addGap(18, 18, 18)
                .addGroup(currentStudentJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbltxtPerson1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(currentStudentJPanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(btnPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHeading, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mainJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(currentStudentJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(currentStudentJPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblHeading)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(currentStudentJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(currentStudentJPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(mainJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientActionPerformed
        // TODO add your handling code here:
        MainPatientPanel patientPanel = new MainPatientPanel(WorkAreaPanel, patientDirectory, personDirectory);
        WorkAreaPanel.add("MainPatientPanel", patientPanel);
        CardLayout cardLayout = (CardLayout) WorkAreaPanel.getLayout();
        cardLayout.next(WorkAreaPanel);
    }//GEN-LAST:event_btnPatientActionPerformed

    private void btnPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonActionPerformed
        // TODO add your handling code here:
        MainPersonPanel personPanel = new MainPersonPanel(WorkAreaPanel, personDirectory);
        WorkAreaPanel.add("MainPersonPanel", personPanel);
        CardLayout cardLayout = (CardLayout) WorkAreaPanel.getLayout();
        cardLayout.next(WorkAreaPanel);

    }//GEN-LAST:event_btnPersonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPatient;
    private javax.swing.JButton btnPerson;
    private javax.swing.JPanel currentStudentJPanel;
    private javax.swing.JPanel currentStudentJPanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JProgressBar jProgressBar3;
    private javax.swing.JProgressBar jProgressBar4;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblPatient;
    private javax.swing.JLabel lblPerson;
    private javax.swing.JLabel lbltxtPatient;
    private javax.swing.JLabel lbltxtPerson1;
    private javax.swing.JLabel lbltxtSummary;
    private javax.swing.JPanel mainJPanel;
    // End of variables declaration//GEN-END:variables
}
