/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.CardLayout;
import models.EncounterHistory;
import models.Patient;
import models.PatientDirectory;
import models.Person;
import models.PersonDirectory;
import ui.ComparePanel.MainComparePanel;
import ui.PatientPanel.MainPatientPanel;
import ui.PersonPanel.MainPersonPanel;

/**
 *
 * @author shreya
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    Person person;
    Patient patient;
    PersonDirectory personDirectory;
    PatientDirectory patientDirectory;
    EncounterHistory encounterHistory;
    public MainJFrame() {
        initComponents();
        person = new Person();
        patient = new Patient();
        encounterHistory = new EncounterHistory();
        personDirectory = new PersonDirectory();
        patientDirectory = new PatientDirectory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPanel = new javax.swing.JSplitPane();
        MenuPanel = new javax.swing.JPanel();
        btnPersonMenu = new javax.swing.JButton();
        btnPatientMenu = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        WorkAreaPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        splitPanel.setDividerLocation(120);
        splitPanel.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        MenuPanel.setBackground(new java.awt.Color(204, 153, 255));
        MenuPanel.setForeground(new java.awt.Color(51, 51, 51));
        MenuPanel.setPreferredSize(new java.awt.Dimension(1212, 40));

        btnPersonMenu.setBackground(new java.awt.Color(255, 255, 255));
        btnPersonMenu.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnPersonMenu.setText("Person");
        btnPersonMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonMenuActionPerformed(evt);
            }
        });

        btnPatientMenu.setBackground(new java.awt.Color(255, 255, 255));
        btnPatientMenu.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnPatientMenu.setText("Patient");
        btnPatientMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatientMenuActionPerformed(evt);
            }
        });

        btnHome.setBackground(new java.awt.Color(255, 255, 255));
        btnHome.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuPanelLayout = new javax.swing.GroupLayout(MenuPanel);
        MenuPanel.setLayout(MenuPanelLayout);
        MenuPanelLayout.setHorizontalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 369, Short.MAX_VALUE)
                .addComponent(btnPersonMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnPatientMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        MenuPanelLayout.setVerticalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPatientMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPersonMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        splitPanel.setTopComponent(MenuPanel);

        WorkAreaPanel.setBackground(new java.awt.Color(153, 102, 255));
        WorkAreaPanel.setForeground(new java.awt.Color(51, 51, 51));
        WorkAreaPanel.setLayout(new java.awt.CardLayout());
        splitPanel.setRightComponent(WorkAreaPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(splitPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 988, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(splitPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPersonMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonMenuActionPerformed
        // TODO add your handling code here:
        MainPersonPanel mainPersonPanel = new MainPersonPanel(WorkAreaPanel, personDirectory );
        WorkAreaPanel.add("MainAdminPanel", mainPersonPanel);
        CardLayout cardLayout = (CardLayout) WorkAreaPanel.getLayout();
        cardLayout.next(WorkAreaPanel);
        
    }//GEN-LAST:event_btnPersonMenuActionPerformed

    private void btnPatientMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientMenuActionPerformed
        // TODO add your handling code here:
        MainPatientPanel mainPatientPanel = new MainPatientPanel(WorkAreaPanel, patientDirectory, personDirectory);
        WorkAreaPanel.add("MainPatientPanel", mainPatientPanel);
        CardLayout cardLayout = (CardLayout) WorkAreaPanel.getLayout();
        cardLayout.next(WorkAreaPanel);
    }//GEN-LAST:event_btnPatientMenuActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        DashboardPanel dashboardPanel = new DashboardPanel(WorkAreaPanel, personDirectory);
        WorkAreaPanel.add("DashboardPanel", dashboardPanel);
        CardLayout cardLayout = (CardLayout) WorkAreaPanel.getLayout();
        cardLayout.next(WorkAreaPanel);
        
        
        
    }//GEN-LAST:event_btnHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MenuPanel;
    private javax.swing.JPanel WorkAreaPanel;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnPatientMenu;
    private javax.swing.JButton btnPersonMenu;
    private javax.swing.JSplitPane splitPanel;
    // End of variables declaration//GEN-END:variables
}
