/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.PatientPanel;

import java.awt.CardLayout;
import javax.swing.JPanel;
import models.Patient;
import models.PatientDirectory;
import models.Person;
import models.PersonDirectory;

/**
 *
 * @author shreya
 */
public class MainPatientPanel extends javax.swing.JPanel {

    /**
     * Creates new form MainPatientPanel
     */
    Patient patient;
    Person person;
    private JPanel WorkAreaPanel;
    PatientDirectory patientDirectory;
    PersonDirectory personDirectory;
    public MainPatientPanel(JPanel WorkAreaPanel, PatientDirectory patientDirectory, PersonDirectory personDirectory) {
        initComponents();
        this.patient = patient;
        this.WorkAreaPanel = WorkAreaPanel;
        this.patientDirectory = patientDirectory;
        this.personDirectory = personDirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblHeading = new javax.swing.JLabel();
        btnCreatePatient = new javax.swing.JButton();
        btnViewPatient = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(153, 102, 255));

        lblHeading.setBackground(new java.awt.Color(255, 255, 255));
        lblHeading.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        lblHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeading.setText("PATIENT DASHBOARD");

        btnCreatePatient.setBackground(new java.awt.Color(255, 255, 255));
        btnCreatePatient.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnCreatePatient.setText("Create Patient");
        btnCreatePatient.setPreferredSize(new java.awt.Dimension(140, 30));
        btnCreatePatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreatePatientActionPerformed(evt);
            }
        });

        btnViewPatient.setBackground(new java.awt.Color(255, 255, 255));
        btnViewPatient.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnViewPatient.setText("Manage Patient");
        btnViewPatient.setPreferredSize(new java.awt.Dimension(140, 30));
        btnViewPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPatientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblHeading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnViewPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCreatePatient, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 307, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblHeading)
                .addGap(148, 148, 148)
                .addComponent(btnCreatePatient, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addComponent(btnViewPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(226, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreatePatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreatePatientActionPerformed
        // TODO add your handling code here:
        CreatePatientPanel createView = new CreatePatientPanel(WorkAreaPanel, patientDirectory, personDirectory);
        WorkAreaPanel.add("CreatePatientPanel", createView);
        CardLayout cardLayout = (CardLayout) WorkAreaPanel.getLayout();
        cardLayout.next(WorkAreaPanel);
        
        
    }//GEN-LAST:event_btnCreatePatientActionPerformed

    private void btnViewPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPatientActionPerformed
        // TODO add your handling code here:
        ManagePatientPanel manageView = new ManagePatientPanel(WorkAreaPanel, patientDirectory, personDirectory);
        WorkAreaPanel.add("ManagePatientPanel", manageView);
        CardLayout cardLayout = (CardLayout) WorkAreaPanel.getLayout();
        cardLayout.next(WorkAreaPanel);
    }//GEN-LAST:event_btnViewPatientActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreatePatient;
    private javax.swing.JButton btnViewPatient;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblHeading;
    // End of variables declaration//GEN-END:variables
}
